### ISSUE TITLE
iterative validation for list of objects?

### ISSUE THREAD

**Issue by avoidik** [alecthomas/voluptuous#385]
hello,

could you please help me a bit, is it possible to define an iterative validation for the following structure

```yaml
- name: random
  owner: bob
  source:
  - type: a
    param: robert
  - type: b
    param: jim
  - type: c
    param: frank
    data:
      aa: sally
      bb: berta
      cc: irena
      dd: helen
```

here it is my attempt to wrap it into `Schema`, not quite sure how to proceed with `type: c` and is it even correct?

```python
ValidationSchema = Schema([{
    Optional('name'): str,
    Required('owner'): All('bob', msg='The only owner should be Bob'),
    Required('source'): [{
        Required('type'): All("a", "b", "c"),
        Required('param'): str,
        Extra('data'): dict
    }]
}])
```
